
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rscombd
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }
       String locations [] = {"Toronto", "Colombo", "Jamaica ", "Athens", "Dhaka", "Chittagong", "London", "New York ", "Lisbon ", "Paris"};
    public void populate()
    {
       DefaultComboBoxModel dm = new DefaultComboBoxModel(locations);
       jComboBox_from.setModel(dm);
     
        
    }
    public String tripz;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_license = new javax.swing.JTextField();
        jComboBox_travelclass = new javax.swing.JComboBox<>();
        jTextField_tlocation = new javax.swing.JTextField();
        jTextField_estimate = new javax.swing.JTextField();
        jDateChooser_date = new com.toedter.calendar.JDateChooser();
        jButton_license = new javax.swing.JButton();
        jButton_class = new javax.swing.JButton();
        jButton_price = new javax.swing.JButton();
        jButton_from = new javax.swing.JButton();
        jButton_date = new javax.swing.JButton();
        jButton_location = new javax.swing.JButton();
        jButton_time = new javax.swing.JButton();
        jButton_totaltime = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox_price = new javax.swing.JComboBox<>();
        jComboBox_ttime = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jComboBox_from = new javax.swing.JComboBox<>();
        jComboBox_to = new javax.swing.JComboBox<>();
        jLabel_tripid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update info ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tripd ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Airplane License no");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Travel class");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ticket price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("From");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Transit Location");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Transit Time");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Estimated Travel time");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("To");

        jTextField_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_licenseActionPerformed(evt);
            }
        });

        jComboBox_travelclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Business Class", "Economy Class" }));
        jComboBox_travelclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_travelclassActionPerformed(evt);
            }
        });

        jButton_license.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_license.setText("Update license no");
        jButton_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_licenseActionPerformed(evt);
            }
        });

        jButton_class.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_class.setText("Update Travel class");
        jButton_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_classActionPerformed(evt);
            }
        });

        jButton_price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_price.setText("Edit price");
        jButton_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_priceActionPerformed(evt);
            }
        });

        jButton_from.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_from.setText("Edit arrival and destination");
        jButton_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fromActionPerformed(evt);
            }
        });

        jButton_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_date.setText("Update date");
        jButton_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dateActionPerformed(evt);
            }
        });

        jButton_location.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_location.setText("Update location");
        jButton_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_locationActionPerformed(evt);
            }
        });

        jButton_time.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_time.setText("Update time");
        jButton_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timeActionPerformed(evt);
            }
        });

        jButton_totaltime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_totaltime.setText("Update total time");
        jButton_totaltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_totaltimeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox_price.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "75", "100", "125", "150", "200", "300", "400" }));

        jComboBox_ttime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 hours", "8 hours", "9 hours", "10 hours", "11 hours", "12 hours", " " }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox_from.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_fromItemStateChanged(evt);
            }
        });

        jLabel_tripid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_tripid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(44, 44, 44))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addComponent(jLabel6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(27, 27, 27)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(22, 22, 22))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(jButton_price))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_license, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton_license))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox_travelclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton_class))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_tlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_ttime, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_location)
                                            .addComponent(jButton_date)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox_to, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_time))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jTextField_estimate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_totaltime))
                            .addComponent(jLabel_tripid, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton_from)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_tripid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_license))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_travelclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_class)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_price)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton_from)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_date))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_location)
                            .addComponent(jTextField_tlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_ttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_time))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_estimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_totaltime))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_travelclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_travelclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_travelclassActionPerformed
        public void tripid(Object s ){
            tripz = s.toString();
            jLabel_tripid.setText(tripz);
        }    
    public boolean checkTrip(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkTrip = false;
        String query = "SELECT * FROM `trip` WHERE `trip_id` =?";
        
        try {
            ps = connect.getConnection().prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkTrip = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Insert.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkTrip;
    }
    private void jButton_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_licenseActionPerformed
        // TODO add your handling code here:
        String tripid =tripz;
        String license = jTextField_license.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
         else if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `A_lic` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,license);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The license no has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_jButton_licenseActionPerformed
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }
    private void jButton_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_classActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String travelclass  = jComboBox_travelclass.getSelectedItem().toString();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `travel_class` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,travelclass);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The travel has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_classActionPerformed

    private void jButton_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_priceActionPerformed
        // TODO add your handling code here:
         String tripid = tripz;
         String price =  jComboBox_price.getSelectedItem().toString();
         int pr = Integer.parseInt(price);	
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `price` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setInt(1,pr);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The price has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_priceActionPerformed

    private void jButton_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_locationActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String tlocation =jTextField_tlocation.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `transit_location` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,tlocation);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit location has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_locationActionPerformed

    private void jButton_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timeActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String ttime = jComboBox_ttime.getSelectedItem().toString();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `transit_time` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,ttime);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit time has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_timeActionPerformed

    private void jButton_totaltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_totaltimeActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String estimate =jTextField_estimate.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `estimated_traveltime` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,estimate);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit time has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
                                               
        
    }//GEN-LAST:event_jButton_totaltimeActionPerformed

    private void jButton_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dateActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String tdate = null;
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
           if(jDateChooser_date.getDate() != null)
        {
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            tdate = dateformat.format(jDateChooser_date.getDate());
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `departure_date` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,tdate);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The departure date has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
                                               
        
         
    }//GEN-LAST:event_jButton_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home rgf = new Home();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_licenseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        View rgf = new View();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fromActionPerformed
        // TODO add your handling code here:
        String tripid = tripz;
        String from =jComboBox_from.getSelectedItem().toString();
        String to = jComboBox_to.getSelectedItem().toString();
       
        if(tripid.equals(""))
        {
            JOptionPane.showMessageDialog(null,"The trip id is compulsory");
        }

        if(checkTrip(tripid))
        {
            PreparedStatement ps;
            ResultSet rs;
            String query = "UPDATE `trip` SET `departure_location` =? WHERE `trip_id` =?";
            String query1 = "UPDATE `trip` SET `arrival_location` =? WHERE `trip_id` =?";

            try {
                ps = connect.getConnection().prepareStatement(query);
                ps.setString(1,from);
                ps.setString(2,tripid);
                ps.executeUpdate();

                ps = connect.getConnection().prepareStatement(query1);
                ps.setString(1,to);
                ps.setString(2,tripid);
                ps.executeUpdate();

                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null,"The locations has been updated");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else {
            JOptionPane.showMessageDialog(null,"The trip id is incorrect");
        }
    }//GEN-LAST:event_jButton_fromActionPerformed

    private void jComboBox_fromItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_fromItemStateChanged
        // TODO add your handling code here:
           Object select = jComboBox_from.getSelectedItem();
             String selection = select.toString();
             ArrayList<String> loc=new ArrayList<String>();
             for(int i =0; i<locations.length ; i++)
             {
                 if(locations[i].equals(selection))
                 {
                 }
                 else{
                     loc.add(locations[i]);
                 }
                 
             }
              String[] item = loc.toArray(new String[loc.size()]); 
             DefaultComboBoxModel jm = new DefaultComboBoxModel(item);
             jComboBox_to.setModel(jm);
        
    }//GEN-LAST:event_jComboBox_fromItemStateChanged
        
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_class;
    private javax.swing.JButton jButton_date;
    private javax.swing.JButton jButton_from;
    private javax.swing.JButton jButton_license;
    private javax.swing.JButton jButton_location;
    private javax.swing.JButton jButton_price;
    private javax.swing.JButton jButton_time;
    private javax.swing.JButton jButton_totaltime;
    private javax.swing.JComboBox<String> jComboBox_from;
    private javax.swing.JComboBox<String> jComboBox_price;
    private javax.swing.JComboBox<String> jComboBox_to;
    private javax.swing.JComboBox<String> jComboBox_travelclass;
    private javax.swing.JComboBox<String> jComboBox_ttime;
    private com.toedter.calendar.JDateChooser jDateChooser_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_tripid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_estimate;
    private javax.swing.JTextField jTextField_license;
    private javax.swing.JTextField jTextField_tlocation;
    // End of variables declaration//GEN-END:variables
}
